### PR TITLE
Make crate more flexible to different versions of lib

### LINKED ISSUE #8: Make crate more flexible to different versions of the library
Unfortunately, when I started implement wrappers I used the latest version of library, but when I tried to compile crate on Debian 9 I figured out that's impossible, because this system doesn't have the latest version of `blkid` in repositories. That's kinda of annoying. To resolve this issue we need to use precompile conditions, in Rust I think it's a features compile conditions. A lot of people use `pkg-config` to find out version of library in system. Rust world has already a wrapper around this utility (follow to the link: https://docs.rs/pkg-config/latest/pkg_config/).
So, the idea is using `pkg-config` crate and setup compiling library code according to the versions of `blkid`.

### PR DESCRIPTION
**Pull request by Silverhorn27**
Use `pkg_config` crate to determine installed version of `libblkid`
library in system.
Enable compile features depend on found version of library.
At now this crate requires at least `2.21.0` version of lib and has
implemented functionality of `2.37.2`.

Closes #8

### CODE REVIEW

**Comment by Silverhorn27** [comment]
Hi @cholcombe973. PR is ready, can you review it?

**Review by cholcombe973 — APPROVED** [review]
Nice work!

**Comment by Silverhorn27** [comment]
@cholcombe973 could you please release version `1.1.0`?

**Comment by Silverhorn27** [comment]
We need to bump minor version, because there were added new functionality.

**Comment by Silverhorn27** [comment]
@cholcombe973 wait for some time to do release. Probably I need to do one more PR, because my static build was failed...

**Pull request merged**
